### ISSUE TITLE
[Bug]: Error when starting Server with Custom Flag

### ISSUE THREAD

**Issue by MrRagtime** [mrxbox98/AdvancedFlags#8]
### Contact Details

ex   mrragtime  /  Mr. Ragtime#3597

### I expected the plugin to load custom flags, and work.
From [latest.log](https://github.com/mrxbox98/AdvancedFlags/files/12889235/latest.log)

- Only happens when I add a custom flag
## Notes
> I'm using 1.20.1 (Not 1.18), plus I'm not using Paper, I'm using [Leaves](https://leavesmc.top/)
##

### Version

1.18

### What server software are you seeing the problem on?

Paper

### Relevant log output

```shell
- [20:38:57 ERROR]: Error occurred while enabling AdvancedFlags v1.3.1 (Is it up to date?)
- java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.add(Object)" because "me.mrxbox98.advancedflags.flags.FlagManager.abbreviations" is null
-         at me.mrxbox98.advancedflags.flags.CustomFlags.loadResource(CustomFlags.java:43) ~[AdvancedFlags-1.3.1.jar:?]
-         at me.mrxbox98.advancedflags.flags.CustomFlags.setupCustomFlags(CustomFlags.java:27) ~[AdvancedFlags-1.3.1.jar:?]
-         at me.mrxbox98.advancedflags.AdvancedFlags.onEnable(AdvancedFlags.java:45) ~[AdvancedFlags-1.3.1.jar:?]
-         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
-         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
-         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:649) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:560) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:629) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
-         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mrxbox98** [comment]
Could you send the custom flag you are adding and the filename of it.

**Comment by MrRagtime** [comment]
yea here

> pu.png

![pu](https://github.com/mrxbox98/AdvancedFlags/assets/134163817/a95775eb-bf00-496a-9e72-fc41f748816c)

**Comment by mrxbox98** [comment]
> yea here
> 
> > pu.png
> 
> ![pu](https://user-images.githubusercontent.com/134163817/275297593-a95775eb-bf00-496a-9e72-fc41f748816c.png)

The large image size and having transparent corners may be an issue. Try a smaller image with no transparency.

**Comment by MrRagtime** [comment]
alright ill try

**Comment by MrRagtime** [comment]
> [09:51:27] [Server thread/INFO]: [AdvancedFlags] Enabling AdvancedFlags v1.3.1*
> [09:51:27] [Server thread/ERROR]: Error occurred while enabling AdvancedFlags v1.3.1 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.add(Object)" because "me.mrxbox98.advancedflags.flags.FlagManager.abbreviations" is null
> 	at me.mrxbox98.advancedflags.flags.CustomFlags.loadResource(CustomFlags.java:43) ~[AdvancedFlags-1.3.1.jar:?]
> 	at me.mrxbox98.advancedflags.flags.CustomFlags.setupCustomFlags(CustomFlags.java:27) ~[AdvancedFlags-1.3.1.jar:?]
> 	at me.mrxbox98.advancedflags.AdvancedFlags.onEnable(AdvancedFlags.java:45) ~[AdvancedFlags-1.3.1.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:649) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:560) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:629) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [09:51:27] [Server thread/INFO]: [AdvancedFlags] Disabling AdvancedFlags v1.3.1

Full Log 
- [latest (3).log](https://github.com/mrxbox98/AdvancedFlags/files/12919496/latest.3.log)
Image used
![pu](https://github.com/mrxbox98/AdvancedFlags/assets/134163817/b72159bb-680d-4a47-ba28-b9c2e3f4e458)
